### ISSUE TITLE
UCRT Not Exporting Natives

### ISSUE THREAD

**Issue by jarobikemp** [Nuix/NuixUCRT#1]
Hello - 
I am trying to get the UCRT to export native files and cannot figure out what the problem is. Can someone help me get this setup, or troubleshoot with me... Is there any documentation that anyone can pass along? Any assistance would be greatly appreciated. 

Thanks in advance! 
Jarobi

**Comment by JuicyDragon** [comment]
UCRT author told me he has assisted you with this already elsewhere, so I am going to close this out.  If I am in error please let me know.
